server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whlg?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  type-aliases-package: com.zr.bean
  mapper-locations: classpath:mapper/*.xml
